type NetworkInfo = {
  shortName: string;
  chainID: number;
  name: string;
  currencySymbol: string;
  baseAPI?: string;
  stagingBaseAPI?: string;
};

export const NETWORKS_WITH_DONATIONS_DEPLOYED = [1, 5, 56, 100, 137];

export const _networkInfo: Array<NetworkInfo> = [
  {
    chainID: 1,
    name: "Ethereum",
    shortName: "eth",
    currencySymbol: "ETH",
    baseAPI: "https://safe-transaction-mainnet.safe.global/api/v1",
  },
  {
    chainID: 5,
    name: "Goerli",
    shortName: "gor",
    currencySymbol: "GOR",
    baseAPI: "https://safe-transaction-goerli.safe.global/api/v1",
  },
  {
    chainID: 10,
    name: "Optimism",
    shortName: "oeth",
    currencySymbol: "OETH",
    baseAPI: "https://safe-transaction-optimism.safe.global/api/v1",
  },
  {
    chainID: 56,
    name: "Binance Smart Chain",
    shortName: "bnb",
    currencySymbol: "BNB",
    baseAPI: "https://safe-transaction-bsc.safe.global/api/v1",
  },
  {
    chainID: 100,
    name: "Gnosis Chain",
    shortName: "gno",
    currencySymbol: "xDAI",
    baseAPI: "https://safe-transaction-gnosis-chain.safe.global/api/v1",
  },
  {
    chainID: 137,
    name: "Polygon",
    shortName: "matic",
    currencySymbol: "MATIC",
    baseAPI: "https://safe-transaction-polygon.safe.global/api/v1",
  },
  {
    chainID: 324,
    name: "Zk Sync Era",
    shortName: "zksync",
    currencySymbol: "ETH",
    baseAPI: "https://safe-transaction-zksync.safe.global/api/v1",
  },
  {
    chainID: 1101,
    name: "Polygon zkEVM",
    shortName: "zkevm",
    currencySymbol: "ETH",
    baseAPI: "https://safe-transaction-zkevm.safe.global/api/v1",
  },
  {
    chainID: 8453,
    name: "Base",
    shortName: "base",
    currencySymbol: "ETH",
    baseAPI: "https://safe-transaction-base.safe.global/api/v1",
  },
  {
    chainID: 42161,
    name: "Arbitrum One",
    shortName: "arb1",
    currencySymbol: "AETH",
    baseAPI: "https://safe-transaction-arbitrum.safe.global/api/v1",
  },
  {
    chainID: 42220,
    name: "Celo",
    shortName: "celo",
    currencySymbol: "Celo",
    baseAPI: "https://safe-transaction-celo.safe.global/api/v1",
  },
  {
    chainID: 43114,
    name: "Avalanche",
    shortName: "avax",
    currencySymbol: "AVAX",
    baseAPI: "https://safe-transaction-avalanche.safe.global/api/v1",
  },
  {
    chainID: 73799,
    name: "Volta",
    shortName: "vt",
    currencySymbol: "VT",
    baseAPI: "https://safe-transaction-volta.safe.global/api/v1",
  },
  {
    chainID: 9001,
    name: "Evmos",
    shortName: "evmos",
    currencySymbol: "EVMOS",
    baseAPI: "https://transaction.safe.evmos.org/api/v1",
    stagingBaseAPI: "https://transaction.safe.evmos.dev/api/v1",
  },
  {
    chainID: 9000,
    name: "Evmos Testnet",
    shortName: "evmos-testnet",
    currencySymbol: "tEVMOS",
    baseAPI: "https://transaction-testnet.safe.evmos.org/api/v1",
    stagingBaseAPI: "https://transaction-testnet.safe.evmos.dev/api/v1",
  },
  {
    chainID: 2222,
    name: "Kava",
    shortName: "kava",
    currencySymbol: "KAVA",
    baseAPI: "https://transaction.safe.kava.io/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.kava.io/api/v1",
  },
  {
    chainID: 2221,
    name: "Kava Testnet",
    shortName: "kava testnet",
    currencySymbol: "TKAVA",
    baseAPI: "https://transaction-testnet.safe.kava.io/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.kava.io/api/v1",
  },
  {
    chainID: 60808,
    name: "BOB Mainnet",
    shortName: "bob mainnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.gobob.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.gobob.xyz/api/v1",
  },
  {
    chainID: 111,
    name: "BOB Testnet",
    shortName: "bob testnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.gobob.xyz/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.gobob.xyz/api/v1",
  },
  {
    chainID: 808813,
    name: "BOB Sepolia",
    shortName: "bob-sepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-sepolia.safe.gobob.xyz/api/v1",
    stagingBaseAPI: "https://transaction-sepolia.staging.safe.gobob.xyz/api/v1",
  },
  {
    chainID: 23294,
    name: "Oasis Sapphire",
    shortName: "sapphire",
    currencySymbol: "ROSE",
    baseAPI: "https://transaction.safe.oasis.io/api/v1",
    stagingBaseAPI: "https://transaction.safe.stg.oasis.io/api/v1",
  },
  {
    chainID: 23295,
    name: "Oasis Sapphire Testnet",
    shortName: "sapphire-testnet",
    currencySymbol: "TEST",
    baseAPI: "https://transaction-testnet.safe.oasis.io/api/v1",
    stagingBaseAPI: "https://transaction-testnet.safe.stg.oasis.io/api/v1",
  },
  {
    chainID: 288,
    name: "Boba Mainnet",
    shortName: "boba",
    currencySymbol: "TEST",
    baseAPI: " https://transaction.safe.boba.network/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.boba.network/api/v1",
  },
  {
    chainID: 56288,
    name: "Boba BNB",
    shortName: "BobaBnb",
    currencySymbol: "TEST",
    baseAPI: "https://transaction-bnb.safe.boba.network/api/v1",
    stagingBaseAPI: "https://transaction-bnb.staging.safe.boba.network/api/v1",
  },
  {
    chainID: 28882,
    name: "Boba Sepolia",
    shortName: "BobaSepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.boba.network/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.boba.network/api/v1",
  },
  {
    chainID: 9728,
    name: "Boba BNB Testnet",
    shortName: "BobaBnbTestnet",
    currencySymbol: "BOBA",
    baseAPI: "https://transaction-bnb-testnet.safe.boba.network/api/v1",
    stagingBaseAPI: "https://transaction-bnb-testnet.staging.safe.boba.network/api/v1",
  },
  {
    chainID: 534352,
    name: "Scroll",
    shortName: "scr",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.scroll.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.scroll.xyz/api/v1",
  },
  {
    chainID: 534351,
    name: "Scroll Sepolia",
    shortName: "scr-sepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-sepolia.safe.scroll.xyz/api/v1",
    stagingBaseAPI: "https://transaction-sepolia.staging.safe.scroll.xyz/api/v1",
  },
  {
    chainID: 919,
    name: "Mode Testnet",
    shortName: "modesep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-mode-sepolia.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-mode-sepolia.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 34443,
    name: "Mode",
    shortName: "mode",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-mode.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-mode.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 11155420,
    name: "OP Sepolia Testnet",
    shortName: "opsep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-optimism-sepolia.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-optimism-sepolia.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 424,
    name: "Public Goods Network",
    shortName: "PGN",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-pgn.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-pgn.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 7777777,
    name: "Zora",
    shortName: "zora",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-zora.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-zora.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 999999999,
    name: "Zora Sepolia Testnet",
    shortName: "zsep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-zora-sepolia.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-zora-sepolia.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 167000,
    name: "Taiko Mainnet L2",
    shortName: "tko-mainnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.taiko.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.taiko.xyz/api/v1",
  },
  {
    chainID: 167009,
    name: "Taiko Hekla L2",
    shortName: "tko-hekla",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-hekla.safe.taiko.xyz/api/v1",
    stagingBaseAPI: "https://transaction-hekla.staging.safe.taiko.xyz/api/v1",
  },
  {
    chainID: 4202,
    name: "Lisk Sepolia",
    shortName: "lisksep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-lisk-sepolia.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-lisk-sepolia.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 1135,
    name: "Lisk Mainnet",
    shortName: "lisk",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-lisk.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-lisk.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 252,
    name: "Fraxtal Mainnet",
    shortName: "fraxtal",
    currencySymbol: "frxETH",
    baseAPI: "https://transaction-frax.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-frax.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 2523,
    name: "Fraxtal Sepolia",
    shortName: "fraxtal-sepolia",
    currencySymbol: "frxETH",
    baseAPI: "https://transaction-frax-sepolia.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-frax-sepolia.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 17069,
    name: "Redstone Testnet - Garnet",
    shortName: "garnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-redstone-testnet.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-redstone-testnet.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 690,
    name: "Redstone Mainnet",
    shortName: "redstone",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-redstone.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-redstone.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 7560,
    name: "Cyber Mainnet",
    shortName: "cyeth",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-cyber.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-cyber.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 111557560,
    name: "Cyber Testnet",
    shortName: "cysep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-cyber-testnet.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-cyber-testnet.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 2192,
    name: "Snaxchain",
    shortName: "snaxchain",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-snaxchain.safe.optimism.io/api/v1",
    stagingBaseAPI: "https://transaction-snaxchain.staging.safe.optimism.io/api/v1",
  },
  {
    chainID: 7225878,
    name: "Saakuru Mainnet",
    shortName: "saakuru",
    currencySymbol: "OAS",
    baseAPI: "https://transaction-safe.saakuru.com/api/v1",
    stagingBaseAPI: "https://transaction-safe-stage.saakuru.com/api/v1",
  },
  {
    chainID: 592,
    name: "Astar",
    shortName: "astr",
    currencySymbol: "ASTR",
    baseAPI: "https://transaction.safe.astar.network/api/v1",
    stagingBaseAPI: "https://transaction.staging-safe.astar.network/api/v1",
  },
  {
    chainID: 3776,
    name: "Astar zkEVM",
    shortName: "astar-zkevm",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-zkevm.safe.astar.network/api/v1",
    stagingBaseAPI: "https://transaction-zkevm.staging-safe.astar.network/api/v1",
  },
  {
    chainID: 336,
    name: "Shiden",
    shortName: "sdn",
    currencySymbol: "SDN",
    baseAPI: "https://transaction-shiden.safe.astar.network/api/v1",
    stagingBaseAPI: "https://transaction-shiden.staging-safe.astar.network/api/v1",
  },
  {
    chainID: 6038361,
    name: "zKyoto",
    shortName: "azkyt",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-zkyoto.safe.astar.network/api/v1",
    stagingBaseAPI: "https://transaction-zkyoto.staging-safe.astar.network/api/v1",
  },
  {
    chainID: 81,
    name: "Shibuya",
    shortName: "sby",
    currencySymbol: "SBY",
    baseAPI: "https://transaction-shibuya.safe.astar.network/api/v1",
    stagingBaseAPI: "https://transaction-shibuya.staging-safe.astar.network/api/v1",
  },
  {
    chainID: 48899,
    name: "Zircuit Testnet",
    shortName: "zircuit-testnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.zircuit.com/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.zircuit.com/api/v1",
  },
  {
    chainID: 48900,
    name: "Zircuit Mainnet",
    shortName: "zircuit-mainnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.zircuit.com/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.zircuit.com/api/v1",
  },
  {
    chainID: 5000,
    name: "Mantle",
    shortName: "mantle",
    currencySymbol: "MNT",
    baseAPI: "https://transaction.multisig.mantle.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.multisig.mantle.xyz/api/v1",
  },
  {
    chainID: 5003,
    name: "Mantle Sepolia",
    shortName: "mnt-sep",
    currencySymbol: "MNT",
    baseAPI: "https://transaction-sepolia.multisig.mantle.xyz/api/v1",
    stagingBaseAPI: "https://transaction-sepolia.staging.multisig.mantle.xyz/api/v1",
  },
  {
    chainID: 2358,
    name: "Kroma Sepolia",
    shortName: "kroma-sepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-kroma-sepolia.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-kroma-sepolia.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 255,
    name: "Kroma",
    shortName: "kroma",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-kroma.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-kroma.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 15003,
    name: "Immutable zkEVM Devnet",
    shortName: "imx-devnet",
    currencySymbol: "dIMX",
    baseAPI: "https://transaction-devnet.safe.immutable.com/api/v1",
    stagingBaseAPI: "https://transaction-devnet.safe.staging.immutable.com/api/v1",
  },
  {
    chainID: 13371,
    name: "Immutable zkEVM",
    shortName: "imx",
    currencySymbol: "IMX",
    baseAPI: "https://transaction.safe.immutable.com/api/v1",
    stagingBaseAPI: "https://transaction.safe.staging.immutable.com/api/v1",
  },
  {
    chainID: 13473,
    name: "Immutable zkEVM Testnet",
    shortName: "imx-testnet",
    currencySymbol: "tIMX",
    baseAPI: "https://transaction-testnet.safe.immutable.com/api/v1",
    stagingBaseAPI: "https://transaction-testnet.safe.staging.immutable.com/api/v1",
  },
  {
    chainID: 1666600000,
    name: "Harmony",
    shortName: "hmy-s0",
    currencySymbol: "ONE",
    baseAPI: "https://transaction.multisig.harmony.one/api/v1",
    stagingBaseAPI: "https://transaction.staging-safe.harmony.one/api/v1",
  },
  {
    chainID: 1666700000,
    name: "Harmony Testnet",
    shortName: "hmy-b-s0",
    currencySymbol: "ONE",
    baseAPI: "https://transaction-testnet.multisig.harmony.one/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging-safe.harmony.one/api/v1",
  },
  {
    chainID: 59144,
    name: "Linea",
    shortName: "linea",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.linea.build/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.linea.build/api/v1",
  },
  {
    chainID: 59140,
    name: "Linea Goerli",
    shortName: "linea-testnet",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.linea.build/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.linea.build/api/v1",
  },
  {
    chainID: 59141,
    name: "Linea Sepolia",
    shortName: "linea-sepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-sepolia.staging.safe.linea.build/api/v1",
    stagingBaseAPI: "https://transaction-sepolia.staging.safe.linea.build/api/v1",
  },
  {
    chainID: 1284,
    name: "Moonbeam",
    shortName: "mbeam",
    currencySymbol: "GLMR",
    baseAPI: "https://transaction.multisig.moonbeam.network/api/v1",
    stagingBaseAPI: "https://transaction.staging.multisig.moonbeam.network/api/v1",
  },
  {
    chainID: 1285,
    name: "Moonriver",
    shortName: "mriver",
    currencySymbol: "MOVR",
    baseAPI: "https://transaction.moonriver.multisig.moonbeam.network/api/v1",
    stagingBaseAPI: "https://transaction.moonriver.staging.multisig.moonbeam.network/api/v1",
  },
  {
    chainID: 1287,
    name: "Moonbase",
    shortName: "mbase",
    currencySymbol: "DEV",
    baseAPI: "https://transaction.moonbase.multisig.moonbeam.network/api/v1",
    stagingBaseAPI: "https://transaction.moonbase.staging.multisig.moonbeam.network/api/v1",
  },
  {
    chainID: 1111,
    name: "WEMIX3.0 Mainnet",
    shortName: "wemix",
    currencySymbol: "WEMIX",
    baseAPI: "https://transaction-wemix.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-wemix.safe.protofire.io/api/v1",
  },
  {
    chainID: 1112,
    name: "WEMIX3.0 Testnet",
    shortName: "twemix",
    currencySymbol: "tWEMIX",
    baseAPI: "https://transaction-wemix-testnet.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-wemix-testnet.safe.protofire.io/api/v1",
  },
  {
    chainID: 30,
    name: "RSK Mainnet",
    shortName: "rsk",
    currencySymbol: "RBTC",
    baseAPI: "https://transaction.safe.rootstock.io/api/v1",
    stagingBaseAPI: "https://transaction.safe.rootstock.io/api/v1",
  },
  {
    chainID: 31,
    name: "RSK Testnet",
    shortName: "trsk",
    currencySymbol: "tRBTC",
    baseAPI: "https://transaction-testnet.safe.rootstock.io/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.rootstock.io/api/v1",
  },
  {
    chainID: 17000,
    name: "Ethereum Holesky Testnet",
    shortName: "holesky",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-holesky.holesky-safe.protofire.io/api/v1",
  },
  {
    chainID: 2741,
    name: "Abstract Mainnet",
    shortName: "abstract",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.abs.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.abs.xyz/api/v1",
  },
  {
    chainID: 11124,
    name: "Abstract Sepolia",
    shortName: "abstract-sepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.abs.xyz/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.abs.xyz/api/v1",
  },
  {
    chainID: 80069,
    name: "Berachain Bepolia",
    shortName: "berachain-bepolia",
    currencySymbol: "BERA",
    baseAPI: "https://transaction-bepolia.safe.berachain.com/api/v1",
    stagingBaseAPI: "https://transaction-bepolia.staging.safe.berachain.com/api/v1",
  },
  {
    chainID: 80094,
    name: "Berachain",
    shortName: "berachain",
    currencySymbol: "BERA",
    baseAPI: "https://transaction.safe.berachain.com/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.berachain.com/api/v1",
  },
  {
    chainID: 2187,
    name: "Game7",
    shortName: "g7",
    currencySymbol: "G7",
    baseAPI: "https://transaction.safe.game7.io/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.game7.io/api/v1",
  },
  {
    chainID: 1625,
    name: "Gravity Alpha Mainnet",
    shortName: "gravity",
    currencySymbol: "G",
    baseAPI: "https://transaction.safe.gravity.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.gravity.xyz/api/v1",
  },
  {
    chainID: 13746,
    name: "Game7 Testnet",
    shortName: "g7t",
    currencySymbol: "TG7T",
    baseAPI: "https://transaction-testnet.staging.safe.game7.io/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.game7.io/api/v1",
  },
  {
    chainID: 13505,
    name: "Gravity Alpha Testnet Sepolia",
    shortName: "gravitysep",
    currencySymbol: "G",
    baseAPI: "https://transaction-testnet.safe.gravity.xyz/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.gravity.xyz/api/v1",
  },
  {
    chainID: 360,
    name: "Shape",
    shortName: "shape",
    currencySymbol: "ETH",
    baseAPI: "https://transaction.safe.shape.network/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.shape.network/api/v1",
  },
  {
    chainID: 11011,
    name: "Shape Sepolia Testnet",
    shortName: "shapesep",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-testnet.safe.shape.network/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.shape.network/api/v1",
  },
  {
    chainID: 660279,
    name: "Xai Mainnet",
    shortName: "xai",
    currencySymbol: "XAI",
    baseAPI: "https://transaction.safe.xai.games/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.xai.games/api/v1",
  },
  {
    chainID: 37714555429,
    name: "Xai Testnet v2",
    shortName: "xaitestnet",
    currencySymbol: "sXAI",
    baseAPI: "https://transaction-testnet.safe.xai.games/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.xai.games/api/v1",
  },
  {
    chainID: 1328,
    name: "Sei Testnet",
    shortName: "sei-testnet",
    currencySymbol: "SEI",
    baseAPI: "https://transaction-testnet.sei-safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.sei-safe.protofire.io/api/v1",
  },
  {
    chainID: 1329,
    name: "Sei Network",
    shortName: "sei",
    currencySymbol: "SEI",
    baseAPI: "https://transaction.sei-safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction.staging.sei-safe.protofire.io/api/v1",
  },
  {
    chainID: 713715,
    name: "Sei Devnet",
    shortName: "sei-devnet",
    currencySymbol: "SEI",
    baseAPI: "https://transaction-devnet.sei-safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-devnet.staging.sei-safe.protofire.io/api/v1",
  },
  {
    chainID: 41923,
    name: "EDU Chain",
    shortName: "edu-chain",
    currencySymbol: "EDU",
    baseAPI: "https://transaction.safe.educhain.xyz/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.educhain.xyz/api/v1",
  },
  {
    chainID: 656476,
    name: "EDU Chain Testnet",
    shortName: "open-campus-codex",
    currencySymbol: "EDU",
    baseAPI: "https://transaction-testnet.safe.educhain.xyz/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.educhain.xyz/api/v1",
  },
  {
    chainID: 5888,
    name: "MANTRA Chain EVM",
    shortName: "mantra_evm",
    currencySymbol: "OM",
    baseAPI: "https://transaction-mantra.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-mantra.w3.safe.protofire.io/api/v1",
  },
  {
    chainID: 5887,
    name: "MANTRACHAIN Testnet",
    shortName: "dukong",
    currencySymbol: "OM",
    baseAPI: "https://transaction-mantra-testnet.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-mantra-testnet.w3.safe.protofire.io/api/v1",
  },
  {
    chainID: 81457,
    name: "Blast Mainnet",
    shortName: "blast",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-blast.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-blast.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 168587773,
    name: "Blast Sepolia",
    shortName: "blastsepolia",
    currencySymbol: "ETH",
    baseAPI: "https://transaction-blast-testnet.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-blast-testnet.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 9745,
    name: "Plasma Mainnet",
    shortName: "plasma",
    currencySymbol: "XPL",
    baseAPI: "https://transaction-plasma.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-plasma.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 9746,
    name: "Plasma Testnet",
    shortName: "plasma-testnet",
    currencySymbol: "XPL",
    baseAPI: "https://transaction-plasma-testnet.safe.protofire.io/api/v1",
    stagingBaseAPI: "https://transaction-plasma-testnet.stage.safe.protofire.io/api/v1",
  },
  {
    chainID: 7001,
    name: "ZetaChain Testnet",
    shortName: "zetachain-athens",
    currencySymbol: "ZETA",
    baseAPI: "https://transaction-testnet.safe.zetachain.com/api/v1",
    stagingBaseAPI: "https://transaction-testnet.staging.safe.zetachain.com/api/v1",
  },
  {
    chainID: 7000,
    name: "ZetaChain Mainnet",
    shortName: "zetachain-mainnet",
    currencySymbol: "ZETA",
    baseAPI: "https://transaction.safe.zetachain.com/api/v1",
    stagingBaseAPI: "https://transaction.staging.safe.zetachain.com/api/v1",
  },
  {
    chainID: 5064014,
    name: "Ethereal",
    shortName: "ethereal",
    currencySymbol: "USDe",
    baseAPI: "https://transaction.safe.ethereal.trade/api/v1",
    stagingBaseAPI: "https://transaction.safe.etherealtest.net/api/v1",
  },
  {
    chainID: 13374202,
    name: "Ethereal Testnet",
    shortName: "ethereal-testnet-0",
    currencySymbol: "USDe",
    baseAPI: "https://transaction-testnet.safe.ethereal.trade/api/v1",
    stagingBaseAPI: "https://transaction-testnet.safe.etherealtest.net/api/v1",
  },
];

export const networkInfo = new Map<number, NetworkInfo>(_networkInfo.map((info) => [info.chainID, info]));
